### ISSUE TITLE
Missing files in checkpoints

### ISSUE THREAD

**Issue by petrikoz** [lbf4616/ContainerNumber-OCR#6]
Hi. I tried to load your checkpoints, but they are missing files. 
Could you please add the missing files?

Missing files:

* `ckpt/recognition_h/model_all.ckpt-8000`
* `ckpt/recognition_v/model_all.ckpt-146000`

**Comment by movie4** [comment]
@lbf4616 — please add missing files, Thanks!

**Comment by lbf4616** [comment]
Please download those models from google drive which is linked in the readme.

**Comment by movie4** [comment]
@lbf4616  — thanks for your answer, but there are no necessary files, I am attaching  GD screenshots

![Screenshot 2022-06-29 at 11 45 24](https://user-images.githubusercontent.com/1005998/176369988-4a4911f6-c2b3-467b-9224-6913859124ea.png)

Missing
`ckpt/recognition_h/model_all.ckpt-8000`

![Screenshot 2022-06-29 at 11 45 57](https://user-images.githubusercontent.com/1005998/176370004-8ee727e4-5c50-4d64-bd40-9fc05a2d453e.png)

Missing
`ckpt/recognition_v/model_all.ckpt-146000`

**Comment by lbf4616** [comment]
Hi, model_all.ckpt-146000 & model_all.ckpt-8000 is the basename of all models I uploaded, you can try the latest code.
